# Generated by Django 3.1.5 on 2021-01-13 16:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(default=datetime.datetime.now, verbose_name='접수날짜')),
                ('company_name', models.CharField(max_length=100, verbose_name='회사명')),
                ('sourcing', models.CharField(max_length=20, null=True, verbose_name='Sourcing')),
                ('company_field', models.CharField(max_length=100, null=True, verbose_name='사업영역')),
                ('memo', models.TextField(null=True, verbose_name='메모')),
                ('is_invest', models.BooleanField(default=False, verbose_name='투자진행')),
                ('receipt_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_detail', models.TextField(null=True, verbose_name='세부사항')),
                ('is_acctive', models.BooleanField(default=True, verbose_name='진행여부')),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_review', to='deallist.receiptlist')),
                ('review_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
