# Generated by Django 3.1.5 on 2021-01-25 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('posts_chunk_size', models.IntegerField(default=10)),
                ('post_pages_nav_chunk_size', models.IntegerField(default=10)),
                ('comments_chunk_size', models.IntegerField(default=5)),
                ('comment_pages_nav_chunk_size', models.IntegerField(default=10)),
                ('is_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('page_view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('ip', models.GenericIPAddressField(default='', null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='board.board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditedPostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('ip', models.GenericIPAddressField(default='', null=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(default='', null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('editedPostHistory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.editedposthistory')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('appr_line', models.CharField(choices=[('A', '결재'), ('B', '합의'), ('C', '참조')], default='A', max_length=1)),
                ('appr_priority', models.IntegerField(default=0)),
                ('appr_state', models.CharField(choices=[('NY', '미결'), ('AC', '승인'), ('RT', '반려')], default='NY', max_length=2)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
