# Generated by Django 3.1.5 on 2021-01-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='appr_state',
            field=models.CharField(choices=[('NY', '미결'), ('AC', '승인'), ('RT', '반려')], default='NY', max_length=2),
        ),
    ]
