# Generated by Django 3.1.5 on 2021-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
